import csv

from manipulação_csv.Exercicios.treinadores import pokemons


def pokemon_treinador():
   pokemons = [
    {"nome": "Metagross", "tipo": "Fantasma", "nivel": 41, "treinador": "Ash Ketchum"},
    {"nome": "Typhlosion", "tipo": "Pedra", "nivel": 90, "treinador": "Misty"},
    {"nome": "Mudsdale", "tipo": "Dragão", "nivel": 47, "treinador": "Brock"},
    {"nome": "Lucario", "tipo": "Elétrico", "nivel": 36, "treinador": "May"},
    {"nome": "Haxorus", "tipo": "Pedra", "nivel": 50, "treinador": "Dawn"},
    {"nome": "Tinkaton", "tipo": "Aço", "nivel": 70, "treinador": "Iris"},
    {"nome": "Hydreigon", "tipo": "Gelo", "nivel": 37, "treinador": "Cilan"},
    {"nome": "Lycanroc", "tipo": "Psíquico", "nivel": 78, "treinador": "Serena"},
    {"nome": "Clodsire", "tipo": "Normal", "nivel": 66, "treinador": "Kiawe"},
    {"nome": "Noivern", "tipo": "Inseto", "nivel": 37, "treinador": "Goh"},
    {"nome": "Hydreigon", "tipo": "Elétrico", "nivel": 50, "treinador": "Ash Ketchum"},
    {"nome": "Aggron", "tipo": "Grama", "nivel": 36, "treinador": "Misty"},
    {"nome": "Noivern", "tipo": "Noturno", "nivel": 51, "treinador": "Brock"},
    {"nome": "Flygon", "tipo": "Dragão", "nivel": 84, "treinador": "May"},
    {"nome": "Metagross", "tipo": "Normal", "nivel": 100, "treinador": "Dawn"},
    {"nome": "Iron Valiant", "tipo": "Normal", "nivel": 54, "treinador": "Iris"},
    {"nome": "Kommo-o", "tipo": "Venenoso", "nivel": 42, "treinador": "Cilan"},
    {"nome": "Tyrantrum", "tipo": "Noturno", "nivel": 74, "treinador": "Serena"},
    {"nome": "Mimikyu", "tipo": "Grama", "nivel": 41, "treinador": "Kiawe"},
    {"nome": "Staraptor", "tipo": "Inseto", "nivel": 70, "treinador": "Goh"},
    {"nome": "Infernape", "tipo": "Pedra", "nivel": 94, "treinador": "Ash Ketchum"},
    {"nome": "Emboar", "tipo": "Grama", "nivel": 39, "treinador": "Misty"},
    {"nome": "Salamence", "tipo": "Normal", "nivel": 45, "treinador": "Brock"},
    {"nome": "Toxtricity", "tipo": "Noturno", "nivel": 45, "treinador": "May"},
    {"nome": "Palafin", "tipo": "Fogo", "nivel": 41, "treinador": "Dawn"},
    {"nome": "Tyranitar", "tipo": "Lutador", "nivel": 45, "treinador": "Iris"},
    {"nome": "Squirtle", "tipo": "Psíquico", "nivel": 65, "treinador": "Cilan"},
    {"nome": "Infernape", "tipo": "Elétrico", "nivel": 93, "treinador": "Serena"},
    {"nome": "Aegislash", "tipo": "Elétrico", "nivel": 42, "treinador": "Kiawe"},
    {"nome": "Rillaboom", "tipo": "Fogo", "nivel": 67, "treinador": "Goh"},
    {"nome": "Volcarona", "tipo": "Fogo", "nivel": 84, "treinador": "Ash Ketchum"},
    {"nome": "Bewear", "tipo": "Pedra", "nivel": 36, "treinador": "Misty"},
    {"nome": "Walrein", "tipo": "Lutador", "nivel": 48, "treinador": "Brock"},
    {"nome": "Snorlax", "tipo": "Água", "nivel": 42, "treinador": "May"},
    {"nome": "Goodra", "tipo": "Água", "nivel": 93, "treinador": "Dawn"},
    {"nome": "Kingdra", "tipo": "Noturno", "nivel": 58, "treinador": "Iris"},
    {"nome": "Swampert", "tipo": "Gelo", "nivel": 54, "treinador": "Cilan"},
    {"nome": "Pikachu", "tipo": "Dragão", "nivel": 77, "treinador": "Serena"},
    {"nome": "Machamp", "tipo": "Venenoso", "nivel": 57, "treinador": "Kiawe"},
    {"nome": "Salazzle", "tipo": "Água", "nivel": 49, "treinador": "Goh"},
    {"nome": "Emboar", "tipo": "Dragão", "nivel": 67, "treinador": "Ash Ketchum"},
    {"nome": "Gardevoir", "tipo": "Noturno", "nivel": 89, "treinador": "Misty"},
    {"nome": "Meganium", "tipo": "Terra", "nivel": 62, "treinador": "Brock"},
    {"nome": "Typhlosion", "tipo": "Dragão", "nivel": 39, "treinador": "May"},
    {"nome": "Iron Valiant", "tipo": "Aço", "nivel": 64, "treinador": "Dawn"},
    {"nome": "Hawlucha", "tipo": "Pedra", "nivel": 46, "treinador": "Iris"},
    {"nome": "Cinderace", "tipo": "Aço", "nivel": 81, "treinador": "Cilan"},
    {"nome": "Gardevoir", "tipo": "Voador", "nivel": 76, "treinador": "Serena"},
    {"nome": "Aggron", "tipo": "Fogo", "nivel": 44, "treinador": "Kiawe"},
    {"nome": "Ampharos", "tipo": "Fada", "nivel": 79, "treinador": "Goh"},
    {"nome": "Kommo-o", "tipo": "Fantasma", "nivel": 76, "treinador": "Ash Ketchum"},
    {"nome": "Mudsdale", "tipo": "Grama", "nivel": 87, "treinador": "Misty"},
    {"nome": "Lapras", "tipo": "Terra", "nivel": 49, "treinador": "Brock"},
    {"nome": "Emboar", "tipo": "Normal", "nivel": 94, "treinador": "May"},
    {"nome": "Meganium", "tipo": "Aço", "nivel": 43, "treinador": "Dawn"},
    {"nome": "Quaquaval", "tipo": "Fogo", "nivel": 70, "treinador": "Iris"},
    {"nome": "Snorlax", "tipo": "Fogo", "nivel": 48, "treinador": "Cilan"},
    {"nome": "Snorlax", "tipo": "Aço", "nivel": 74, "treinador": "Serena"},
    {"nome": "Mismagius", "tipo": "Dragão", "nivel": 34, "treinador": "Kiawe"},
    {"nome": "Cofagrigus", "tipo": "Pedra", "nivel": 49, "treinador": "Goh"},
    {"nome": "Infernape", "tipo": "Terra", "nivel": 42, "treinador": "Ash Ketchum"},
    {"nome": "Bewear", "tipo": "Noturno", "nivel": 72, "treinador": "Misty"},
    {"nome": "Hawlucha", "tipo": "Noturno", "nivel": 81, "treinador": "Brock"},
    {"nome": "Pikachu", "tipo": "Fogo", "nivel": 39, "treinador": "May"},
    {"nome": "Metagross", "tipo": "Normal", "nivel": 76, "treinador": "Dawn"},
    {"nome": "Garchomp", "tipo": "Voador", "nivel": 43, "treinador": "Iris"},
    {"nome": "Gallade", "tipo": "Elétrico", "nivel": 33, "treinador": "Cilan"},
    {"nome": "Toxapex", "tipo": "Venenoso", "nivel": 98, "treinador": "Serena"},
    {"nome": "Corviknight", "tipo": "Fogo", "nivel": 49, "treinador": "Kiawe"},
    {"nome": "Malamar", "tipo": "Inseto", "nivel": 49, "treinador": "Goh"},
    {"nome": "Infernape", "tipo": "Grama", "nivel": 85, "treinador": "Ash Ketchum"},
    {"nome": "Squirtle", "tipo": "Psíquico", "nivel": 68, "treinador": "Misty"},
    {"nome": "Lycanroc", "tipo": "Dragão", "nivel": 48, "treinador": "Brock"},
    {"nome": "Primarina", "tipo": "Água", "nivel": 82, "treinador": "May"},
    {"nome": "Flygon", "tipo": "Água", "nivel": 61, "treinador": "Dawn"},
    {"nome": "Infernape", "tipo": "Venenoso", "nivel": 70, "treinador": "Iris"},
    {"nome": "Pawmot", "tipo": "Dragão", "nivel": 69, "treinador": "Cilan"},
    {"nome": "Palafin", "tipo": "Grama", "nivel": 75, "treinador": "Serena"},
    {"nome": "Torterra", "tipo": "Grama", "nivel": 40, "treinador": "Kiawe"},
    {"nome": "Goodra", "tipo": "Fada", "nivel": 37, "treinador": "Goh"},
    {"nome": "Lycanroc", "tipo": "Elétrico", "nivel": 89, "treinador": "Ash Ketchum"},
    {"nome": "Alakazam", "tipo": "Fantasma", "nivel": 94, "treinador": "Misty"},
    {"nome": "Emboar", "tipo": "Elétrico", "nivel": 56, "treinador": "Brock"},
    {"nome": "Kingdra", "tipo": "Noturno", "nivel": 92, "treinador": "May"},
    {"nome": "Dragalge", "tipo": "Água", "nivel": 53, "treinador": "Dawn"},
    {"nome": "Metagross", "tipo": "Inseto", "nivel": 87, "treinador": "Iris"},
    {"nome": "Garchomp", "tipo": "Dragão", "nivel": 55, "treinador": "Cilan"},
    {"nome": "Metagross", "tipo": "Inseto", "nivel": 92, "treinador": "Serena"},
    {"nome": "Salazzle", "tipo": "Gelo", "nivel": 92, "treinador": "Kiawe"},
    {"nome": "Clodsire", "tipo": "Normal", "nivel": 33, "treinador": "Goh"},
    {"nome": "Cinderace", "tipo": "Terra", "nivel": 80, "treinador": "Ash Ketchum"},
    {"nome": "Glimmora", "tipo": "Fogo", "nivel": 64, "treinador": "Misty"},
    {"nome": "Greninja", "tipo": "Psíquico", "nivel": 39, "treinador": "Brock"},
    {"nome": "Staraptor", "tipo": "Noturno", "nivel": 97, "treinador": "May"},
    {"nome": "Roserade", "tipo": "Lutador", "nivel": 95, "treinador": "Dawn"},
    {"nome": "Roserade", "tipo": "Fogo", "nivel": 57, "treinador": "Iris"},
    {"nome": "Snorlax", "tipo": "Água", "nivel": 58, "treinador": "Cilan"},
    {"nome": "Primarina", "tipo": "Dragão", "nivel": 87, "treinador": "Serena"},
    {"nome": "Corviknight", "tipo": "Voador", "nivel": 82, "treinador": "Kiawe"},
    {"nome": "Scizor", "tipo": "Fogo", "nivel": 75, "treinador": "Goh"},
    {"nome": "Chandelure", "tipo": "Terra", "nivel": 89, "treinador": "Ash Ketchum"},
    {"nome": "Copperajah", "tipo": "Fantasma", "nivel": 63, "treinador": "Misty"},
    {"nome": "Grimmsnarl", "tipo": "Elétrico", "nivel": 44, "treinador": "Brock"},
    {"nome": "Quaquaval", "tipo": "Voador", "nivel": 43, "treinador": "May"},
    {"nome": "Toxapex", "tipo": "Noturno", "nivel": 69, "treinador": "Dawn"},
    {"nome": "Kingdra", "tipo": "Grama", "nivel": 31, "treinador": "Iris"},
    {"nome": "Salamence", "tipo": "Grama", "nivel": 65, "treinador": "Cilan"},
    {"nome": "Gallade", "tipo": "Psíquico", "nivel": 71, "treinador": "Serena"},
    {"nome": "Aegislash", "tipo": "Venenoso", "nivel": 62, "treinador": "Kiawe"},
    {"nome": "Walrein", "tipo": "Psíquico", "nivel": 55, "treinador": "Goh"},
    {"nome": "Lucario", "tipo": "Venenoso", "nivel": 76, "treinador": "Ash Ketchum"},
    {"nome": "Bewear", "tipo": "Voador", "nivel": 64, "treinador": "Misty"},
    {"nome": "Squirtle", "tipo": "Noturno", "nivel": 36, "treinador": "Brock"},
    {"nome": "Copperajah", "tipo": "Voador", "nivel": 77, "treinador": "May"},
    {"nome": "Alakazam", "tipo": "Normal", "nivel": 39, "treinador": "Dawn"},
    {"nome": "Palafin", "tipo": "Lutador", "nivel": 49, "treinador": "Iris"},
    {"nome": "Umbreon", "tipo": "Voador", "nivel": 99, "treinador": "Cilan"},
    {"nome": "Gardevoir", "tipo": "Terra", "nivel": 75, "treinador": "Serena"},
    {"nome": "Quaquaval", "tipo": "Lutador", "nivel": 80, "treinador": "Kiawe"},
    {"nome": "Kingdra", "tipo": "Noturno", "nivel": 61, "treinador": "Goh"},
    {"nome": "Torterra", "tipo": "Fogo", "nivel": 47, "treinador": "Ash Ketchum"},
    {"nome": "Sceptile", "tipo": "Terra", "nivel": 69, "treinador": "Misty"},
    {"nome": "Dragalge", "tipo": "Psíquico", "nivel": 41, "treinador": "Brock"},
    {"nome": "Lucario", "tipo": "Pedra", "nivel": 54, "treinador": "May"},
    {"nome": "Bulbasaur", "tipo": "Noturno", "nivel": 31, "treinador": "Dawn"},
    {"nome": "Gardevoir", "tipo": "Dragão", "nivel": 36, "treinador": "Iris"},
    {"nome": "Meganium", "tipo": "Fada", "nivel": 51, "treinador": "Cilan"},
    {"nome": "Pawmot", "tipo": "Fogo", "nivel": 75, "treinador": "Serena"},
    {"nome": "Copperajah", "tipo": "Elétrico", "nivel": 50, "treinador": "Kiawe"},
    {"nome": "Noivern", "tipo": "Psíquico", "nivel": 37, "treinador": "Goh"},
    {"nome": "Chandelure", "tipo": "Noturno", "nivel": 30, "treinador": "Ash Ketchum"},
    {"nome": "Walrein", "tipo": "Elétrico", "nivel": 75, "treinador": "Misty"},
    {"nome": "Talonflame", "tipo": "Fada", "nivel": 90, "treinador": "Brock"},
    {"nome": "Machamp", "tipo": "Terra", "nivel": 74, "treinador": "May"},
    {"nome": "Garchomp", "tipo": "Noturno", "nivel": 88, "treinador": "Dawn"},
    {"nome": "Blaziken", "tipo": "Venenoso", "nivel": 55, "treinador": "Iris"},
    {"nome": "Pawmot", "tipo": "Aço", "nivel": 37, "treinador": "Cilan"},
    {"nome": "Hatterene", "tipo": "Gelo", "nivel": 74, "treinador": "Serena"},
    {"nome": "Crobat", "tipo": "Normal", "nivel": 79, "treinador": "Kiawe"},
    {"nome": "Meowscarada", "tipo": "Normal", "nivel": 75, "treinador": "Goh"},
    {"nome": "Quaquaval", "tipo": "Pedra", "nivel": 89, "treinador": "Ash Ketchum"},
    {"nome": "Arcanine", "tipo": "Venenoso", "nivel": 66, "treinador": "Misty"},
    {"nome": "Weavile", "tipo": "Noturno", "nivel": 98, "treinador": "Brock"},
    {"nome": "Hydreigon", "tipo": "Psíquico", "nivel": 47, "treinador": "May"},
    {"nome": "Mudsdale", "tipo": "Inseto", "nivel": 100, "treinador": "Dawn"},
    {"nome": "Gallade", "tipo": "Voador", "nivel": 66, "treinador": "Iris"},
    {"nome": "Torterra", "tipo": "Fada", "nivel": 81, "treinador": "Cilan"},
    {"nome": "Cofagrigus", "tipo": "Fogo", "nivel": 50, "treinador": "Serena"},
    {"nome": "Zoroark", "tipo": "Inseto", "nivel": 78, "treinador": "Kiawe"},
    {"nome": "Toxtricity", "tipo": "Dragão", "nivel": 48, "treinador": "Goh"},
    {"nome": "Palafin", "tipo": "Grama", "nivel": 90, "treinador": "Ash Ketchum"},
    {"nome": "Cinderace", "tipo": "Fogo", "nivel": 81, "treinador": "Misty"},
    {"nome": "Lycanroc", "tipo": "Grama", "nivel": 48, "treinador": "Brock"},
    {"nome": "Infernape", "tipo": "Fogo", "nivel": 46, "treinador": "May"},
    {"nome": "Gardevoir", "tipo": "Elétrico", "nivel": 47, "treinador": "Dawn"},
    {"nome": "Weavile", "tipo": "Elétrico", "nivel": 41, "treinador": "Iris"},
    {"nome": "Tyranitar", "tipo": "Dragão", "nivel": 76, "treinador": "Cilan"},
    {"nome": "Malamar", "tipo": "Elétrico", "nivel": 32, "treinador": "Serena"},
    {"nome": "Rillaboom", "tipo": "Normal", "nivel": 35, "treinador": "Kiawe"},
    {"nome": "Hydreigon", "tipo": "Gelo", "nivel": 34, "treinador": "Goh"},
    {"nome": "Garchomp", "tipo": "Pedra", "nivel": 81, "treinador": "Ash Ketchum"},
    {"nome": "Alakazam", "tipo": "Gelo", "nivel": 75, "treinador": "Misty"},
    {"nome": "Serperior", "tipo": "Pedra", "nivel": 89, "treinador": "Brock"},
    {"nome": "Cinderace", "tipo": "Fada", "nivel": 87, "treinador": "May"},
    {"nome": "Chandelure", "tipo": "Pedra", "nivel": 48, "treinador": "Dawn"},
    {"nome": "Greninja", "tipo": "Venenoso", "nivel": 72, "treinador": "Iris"},
    {"nome": "Gengar", "tipo": "Gelo", "nivel": 30, "treinador": "Cilan"},
    {"nome": "Talonflame", "tipo": "Terra", "nivel": 96, "treinador": "Serena"},
    {"nome": "Malamar", "tipo": "Água", "nivel": 68, "treinador": "Kiawe"},
    {"nome": "Sceptile", "tipo": "Normal", "nivel": 40, "treinador": "Goh"},
    {"nome": "Annihilape", "tipo": "Psíquico", "nivel": 66, "treinador": "Ash Ketchum"},
    {"nome": "Corviknight", "tipo": "Voador", "nivel": 93, "treinador": "Misty"},
    {"nome": "Malamar", "tipo": "Pedra", "nivel": 70, "treinador": "Brock"},
    {"nome": "Annihilape", "tipo": "Fantasma", "nivel": 74, "treinador": "May"},
    {"nome": "Skeledirge", "tipo": "Grama", "nivel": 32, "treinador": "Dawn"},
    {"nome": "Walrein", "tipo": "Psíquico", "nivel": 80, "treinador": "Iris"},
    {"nome": "Mimikyu", "tipo": "Fantasma", "nivel": 65, "treinador": "Cilan"},
    {"nome": "Hydreigon", "tipo": "Noturno", "nivel": 86, "treinador": "Serena"},
    {"nome": "Walrein", "tipo": "Inseto", "nivel": 31, "treinador": "Kiawe"},
    {"nome": "Torterra", "tipo": "Elétrico", "nivel": 37, "treinador": "Goh"},
    {"nome": "Salazzle", "tipo": "Pedra", "nivel": 54, "treinador": "Ash Ketchum"},
    {"nome": "Aegislash", "tipo": "Dragão", "nivel": 30, "treinador": "Misty"},
    {"nome": "Empoleon", "tipo": "Inseto", "nivel": 64, "treinador": "Brock"},
    {"nome": "Tyrantrum", "tipo": "Psíquico", "nivel": 100, "treinador": "May"},
    {"nome": "Garchomp", "tipo": "Lutador", "nivel": 50, "treinador": "Dawn"},
    {"nome": "Lucario", "tipo": "Dragão", "nivel": 35, "treinador": "Iris"},
    {"nome": "Swampert", "tipo": "Fada", "nivel": 97, "treinador": "Cilan"},
    {"nome": "Swampert", "tipo": "Elétrico", "nivel": 65, "treinador": "Serena"},
    {"nome": "Centiskorch", "tipo": "Fantasma", "nivel": 58, "treinador": "Kiawe"},
    {"nome": "Greninja", "tipo": "Aço", "nivel": 41, "treinador": "Goh"},
    {"nome": "Annihilape", "tipo": "Normal", "nivel": 60, "treinador": "Ash Ketchum"},
    {"nome": "Glimmora", "tipo": "Aço", "nivel": 47, "treinador": "Misty"},
    {"nome": "Toxtricity", "tipo": "Voador", "nivel": 69, "treinador": "Brock"},
    {"nome": "Scizor", "tipo": "Normal", "nivel": 45, "treinador": "May"},
    {"nome": "Sylveon", "tipo": "Venenoso", "nivel": 61, "treinador": "Dawn"},
    {"nome": "Meganium", "tipo": "Elétrico", "nivel": 46, "treinador": "Iris"},
    {"nome": "Cinderace", "tipo": "Fantasma", "nivel": 31, "treinador": "Cilan"},
    {"nome": "Dragapult", "tipo": "Fada", "nivel": 41, "treinador": "Serena"},
    {"nome": "Swampert", "tipo": "Psíquico", "nivel": 67, "treinador": "Kiawe"},
    {"nome": "Gardevoir", "tipo": "Venenoso", "nivel": 55, "treinador": "Goh"},
    {"nome": "Hydreigon", "tipo": "Psíquico", "nivel": 76, "treinador": "Ash Ketchum"},
    {"nome": "Glimmora", "tipo": "Grama", "nivel": 80, "treinador": "Misty"},
    {"nome": "Kingdra", "tipo": "Grama", "nivel": 72, "treinador": "Brock"},
    {"nome": "Walrein", "tipo": "Noturno", "nivel": 55, "treinador": "May"},
    {"nome": "Snorlax", "tipo": "Elétrico", "nivel": 49, "treinador": "Dawn"},
    {"nome": "Lucario", "tipo": "Venenoso", "nivel": 86, "treinador": "Iris"},
    {"nome": "Ampharos", "tipo": "Aço", "nivel": 38, "treinador": "Cilan"},
    {"nome": "Crobat", "tipo": "Noturno", "nivel": 92, "treinador": "Serena"},
    {"nome": "Espeon", "tipo": "Lutador", "nivel": 31, "treinador": "Kiawe"},
    {"nome": "Copperajah", "tipo": "Elétrico", "nivel": 100, "treinador": "Goh"},
    {"nome": "Hydreigon", "tipo": "Lutador", "nivel": 56, "treinador": "Ash Ketchum"},
    {"nome": "Volcarona", "tipo": "Normal", "nivel": 62, "treinador": "Misty"},
    {"nome": "Haxorus", "tipo": "Voador", "nivel": 50, "treinador": "Brock"},
    {"nome": "Hydreigon", "tipo": "Grama", "nivel": 42, "treinador": "May"},
    {"nome": "Centiskorch", "tipo": "Pedra", "nivel": 99, "treinador": "Dawn"},
    {"nome": "Malamar", "tipo": "Gelo", "nivel": 85, "treinador": "Iris"},
    {"nome": "Greninja", "tipo": "Dragão", "nivel": 88, "treinador": "Cilan"},
    {"nome": "Scizor", "tipo": "Noturno", "nivel": 87, "treinador": "Serena"},
    {"nome": "Incineroar", "tipo": "Dragão", "nivel": 41, "treinador": "Kiawe"},
    {"nome": "Milotic", "tipo": "Inseto", "nivel": 41, "treinador": "Goh"},
    {"nome": "Hydreigon", "tipo": "Voador", "nivel": 89, "treinador": "Ash Ketchum"},
    {"nome": "Charizard", "tipo": "Normal", "nivel": 93, "treinador": "Misty"},
    {"nome": "Flygon", "tipo": "Inseto", "nivel": 60, "treinador": "Brock"},
    {"nome": "Pawmot", "tipo": "Venenoso", "nivel": 46, "treinador": "May"},
    {"nome": "Emboar", "tipo": "Grama", "nivel": 30, "treinador": "Dawn"},
    {"nome": "Hawlucha", "tipo": "Inseto", "nivel": 32, "treinador": "Iris"},
    {"nome": "Lucario", "tipo": "Fogo", "nivel": 72, "treinador": "Cilan"},
    {"nome": "Copperajah", "tipo": "Noturno", "nivel": 78, "treinador": "Serena"},
    {"nome": "Kingdra", "tipo": "Psíquico", "nivel": 57, "treinador": "Kiawe"},
    {"nome": "Rillaboom", "tipo": "Grama", "nivel": 67, "treinador": "Goh"},
    {"nome": "Tinkaton", "tipo": "Gelo", "nivel": 69, "treinador": "Ash Ketchum"},
    {"nome": "Noivern", "tipo": "Dragão", "nivel": 40, "treinador": "Misty"},
    {"nome": "Feraligatr", "tipo": "Normal", "nivel": 58, "treinador": "Brock"},
    {"nome": "Meowscarada", "tipo": "Fada", "nivel": 77, "treinador": "May"},
    {"nome": "Mimikyu", "tipo": "Fogo", "nivel": 31, "treinador": "Dawn"},
    {"nome": "Gallade", "tipo": "Aço", "nivel": 75, "treinador": "Iris"},
    {"nome": "Pawmot", "tipo": "Terra", "nivel": 96, "treinador": "Cilan"},
    {"nome": "Corviknight", "tipo": "Elétrico", "nivel": 76, "treinador": "Serena"},
    {"nome": "Garchomp", "tipo": "Terra", "nivel": 53, "treinador": "Kiawe"},
    {"nome": "Iron Valiant", "tipo": "Fantasma", "nivel": 80, "treinador": "Goh"},
    {"nome": "Gallade", "tipo": "Voador", "nivel": 42, "treinador": "Ash Ketchum"},
    {"nome": "Flygon", "tipo": "Gelo", "nivel": 94, "treinador": "Misty"},
    {"nome": "Meganium", "tipo": "Terra", "nivel": 96, "treinador": "Brock"},
    {"nome": "Flygon", "tipo": "Aço", "nivel": 48, "treinador": "May"},
    {"nome": "Infernape", "tipo": "Psíquico", "nivel": 76, "treinador": "Dawn"},
    {"nome": "Kingdra", "tipo": "Pedra", "nivel": 98, "treinador": "Iris"},
    {"nome": "Arcanine", "tipo": "Psíquico", "nivel": 94, "treinador": "Cilan"},
    {"nome": "Toxtricity", "tipo": "Fada", "nivel": 49, "treinador": "Serena"},
    {"nome": "Roserade", "tipo": "Aço", "nivel": 37, "treinador": "Kiawe"},
    {"nome": "Bulbasaur", "tipo": "Água", "nivel": 67, "treinador": "Goh"},
    {"nome": "Toxapex", "tipo": "Grama", "nivel": 92, "treinador": "Ash Ketchum"},
    {"nome": "Scizor", "tipo": "Psíquico", "nivel": 97, "treinador": "Misty"},
    {"nome": "Feraligatr", "tipo": "Aço", "nivel": 53, "treinador": "Brock"},
    {"nome": "Salamence", "tipo": "Elétrico", "nivel": 54, "treinador": "May"},
    {"nome": "Corviknight", "tipo": "Fantasma", "nivel": 74, "treinador": "Dawn"},
    {"nome": "Dragalge", "tipo": "Dragão", "nivel": 83, "treinador": "Iris"},
    {"nome": "Pikachu", "tipo": "Fada", "nivel": 99, "treinador": "Cilan"},
    {"nome": "Flygon", "tipo": "Voador", "nivel": 75, "treinador": "Serena"},
    {"nome": "Machamp", "tipo": "Noturno", "nivel": 41, "treinador": "Kiawe"},
    {"nome": "Gallade", "tipo": "Normal", "nivel": 32, "treinador": "Goh"},
    {"nome": "Empoleon", "tipo": "Noturno", "nivel": 76, "treinador": "Ash Ketchum"},
    {"nome": "Malamar", "tipo": "Lutador", "nivel": 83, "treinador": "Misty"},
    {"nome": "Weavile", "tipo": "Gelo", "nivel": 41, "treinador": "Brock"},
    {"nome": "Weavile", "tipo": "Elétrico", "nivel": 80, "treinador": "May"},
    {"nome": "Lycanroc", "tipo": "Noturno", "nivel": 56, "treinador": "Dawn"},
    {"nome": "Milotic", "tipo": "Terra", "nivel": 71, "treinador": "Iris"},
    {"nome": "Machamp", "tipo": "Elétrico", "nivel": 85, "treinador": "Cilan"},
    {"nome": "Sylveon", "tipo": "Inseto", "nivel": 50, "treinador": "Serena"},
    {"nome": "Volcarona", "tipo": "Voador", "nivel": 68, "treinador": "Kiawe"},
    {"nome": "Bewear", "tipo": "Elétrico", "nivel": 86, "treinador": "Goh"},
    {"nome": "Kommo-o", "tipo": "Pedra", "nivel": 39, "treinador": "Ash Ketchum"},
    {"nome": "Annihilape", "tipo": "Pedra", "nivel": 57, "treinador": "Misty"},
    {"nome": "Crobat", "tipo": "Psíquico", "nivel": 40, "treinador": "Brock"},
    {"nome": "Clodsire", "tipo": "Fada", "nivel": 40, "treinador": "May"},
    {"nome": "Noivern", "tipo": "Voador", "nivel": 77, "treinador": "Dawn"},
    {"nome": "Toxapex", "tipo": "Pedra", "nivel": 49, "treinador": "Iris"},
    {"nome": "Lapras", "tipo": "Lutador", "nivel": 56, "treinador": "Cilan"},
    {"nome": "Feraligatr", "tipo": "Gelo", "nivel": 89, "treinador": "Serena"},
    {"nome": "Crobat", "tipo": "Venenoso", "nivel": 54, "treinador": "Kiawe"},
    {"nome": "Incineroar", "tipo": "Fada", "nivel": 98, "treinador": "Goh"},
    {"nome": "Mudsdale", "tipo": "Lutador", "nivel": 77, "treinador": "Ash Ketchum"},
    {"nome": "Mismagius", "tipo": "Fada", "nivel": 49, "treinador": "Misty"},
    {"nome": "Blaziken", "tipo": "Gelo", "nivel": 36, "treinador": "Brock"},
    {"nome": "Flygon", "tipo": "Aço", "nivel": 84, "treinador": "May"},
    {"nome": "Lapras", "tipo": "Psíquico", "nivel": 87, "treinador": "Dawn"},
    {"nome": "Grimmsnarl", "tipo": "Terra", "nivel": 88, "treinador": "Iris"},
    {"nome": "Crobat", "tipo": "Elétrico", "nivel": 70, "treinador": "Cilan"},
    {"nome": "Malamar", "tipo": "Dragão", "nivel": 63, "treinador": "Serena"},
    {"nome": "Mudsdale", "tipo": "Terra", "nivel": 83, "treinador": "Kiawe"},
    {"nome": "Haxorus", "tipo": "Noturno", "nivel": 51, "treinador": "Goh"},
    {"nome": "Decidueye", "tipo": "Grama", "nivel": 49, "treinador": "Ash Ketchum"},
    {"nome": "Noivern", "tipo": "Gelo", "nivel": 51, "treinador": "Misty"},
    {"nome": "Squirtle", "tipo": "Fogo", "nivel": 56, "treinador": "Brock"},
    {"nome": "Chandelure", "tipo": "Fantasma", "nivel": 65, "treinador": "May"},
    {"nome": "Centiskorch", "tipo": "Fada", "nivel": 85, "treinador": "Dawn"},
    {"nome": "Malamar", "tipo": "Dragão", "nivel": 53, "treinador": "Iris"},
    {"nome": "Tinkaton", "tipo": "Inseto", "nivel": 98, "treinador": "Cilan"},
    {"nome": "Staraptor", "tipo": "Inseto", "nivel": 100, "treinador": "Serena"},
    {"nome": "Infernape", "tipo": "Fogo", "nivel": 79, "treinador": "Kiawe"},
    {"nome": "Malamar", "tipo": "Noturno", "nivel": 97, "treinador": "Goh"}
    ]

    with open('pokemon.csv', "w", newline="", encoding="utf-8") as arquivo:
        escritor = csv.writer(arquivo)
        escritor.writerow(["nome", "tipo", "nivel", "treinador"])  # Cabeçalho
        escritor.writerows(pokemons)

    while True:
        print("● ===== POKÉMON DOS TREINADORES ====="
                "● 1 - Listar Pokémon de um treinador"
                "● 2 - Contar Pokémon de um treinador"
                "● 3 - Mostrar Pokémon de maior nível"
                "● 4 - Mostrar Pokémon de menor nível"
                "● 5 - Listar Pokémon de determinado tipo"
                "6 - Voltar ao menu")

            resposta = input("\nDigite sua opção: ")

            if resposta == "1":
                with open("treinador.csv", "r", encoding="utf-8") as arquivo:
                    leitor = csv.DictReader(arquivo)
                    treinador = input("digite o nome do treinador: ")





pokemon_treinador()